language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sjmaddenhart/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sjmaddenhart/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  name: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-181507181603"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY